# Generated by Django 5.2.18 on 2026-10-08 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('core', '0002_seed_rescue_catalogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_gestion_hash', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField()),
                ('contacto_reportante', models.CharField(blank=True, max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_reporte', models.ForeignKey(db_column='id_estado_reporte', on_delete=django.db.models.deletion.PROTECT, related_name='reportes_estado', to='core.valormaestro')),
                ('mascota', models.ForeignKey(blank=True, db_column='id_mascota', null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.mascota')),
                ('tipo_reporte', models.ForeignKey(db_column='id_tipo_reporte', on_delete=django.db.models.deletion.PROTECT, related_name='reportes_tipo', to='core.valormaestro')),
                ('usuario_reportante', models.ForeignKey(blank=True, db_column='id_usuario_reportante', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reporte',
            },
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('zona', models.OneToOneField(db_column='id_zona', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.zona')),
                ('poligono_wkt', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ZonaGeografica',
            },
        ),
        migrations.CreateModel(
            name='CasoRescate',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('justificacion_sin_cupo', models.TextField(blank=True)),
                ('estado_caso', models.ForeignKey(db_column='id_estado_caso', on_delete=django.db.models.deletion.PROTECT, to='core.valormaestro')),
                ('fundacion', models.ForeignKey(db_column='id_fundacion', on_delete=django.db.models.deletion.PROTECT, to='core.fundacion')),
                ('usuario_ultimo_cambio', models.ForeignKey(db_column='id_usuario_ultimo_cambio', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.OneToOneField(db_column='id_reporte', on_delete=django.db.models.deletion.PROTECT, to='rescue.reporte')),
            ],
            options={
                'db_table': 'CasoRescate',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCaso',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.OneToOneField(db_column='id_archivo', on_delete=django.db.models.deletion.PROTECT, to='core.archivodigital')),
                ('caso', models.ForeignKey(db_column='id_caso', on_delete=django.db.models.deletion.PROTECT, to='rescue.casorescate')),
                ('tipo_evidencia', models.ForeignKey(db_column='id_tipo_evidencia', on_delete=django.db.models.deletion.PROTECT, to='core.valormaestro')),
            ],
            options={
                'db_table': 'EvidenciaCaso',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoCaso',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('caso', models.ForeignKey(db_column='id_caso', on_delete=django.db.models.deletion.PROTECT, to='rescue.casorescate')),
                ('estado_anterior', models.ForeignKey(blank=True, db_column='id_estado_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_historial_anterior', to='core.valormaestro')),
                ('estado_nuevo', models.ForeignKey(db_column='id_estado_nuevo', on_delete=django.db.models.deletion.PROTECT, related_name='casos_historial_nuevo', to='core.valormaestro')),
                ('usuario_actor', models.ForeignKey(db_column='id_usuario_actor', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HistorialEstadoCaso',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoReporte',
            fields=[
                ('id_historial_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('estado_anterior', models.ForeignKey(blank=True, db_column='id_estado_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_historial_anterior', to='core.valormaestro')),
                ('estado_nuevo', models.ForeignKey(db_column='id_estado_nuevo', on_delete=django.db.models.deletion.PROTECT, related_name='reportes_historial_nuevo', to='core.valormaestro')),
                ('usuario_actor', models.ForeignKey(blank=True, db_column='id_usuario_actor', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.PROTECT, to='rescue.reporte')),
            ],
            options={
                'db_table': 'HistorialEstadoReporte',
            },
        ),
        migrations.CreateModel(
            name='ReporteUbicacion',
            fields=[
                ('reporte', models.OneToOneField(db_column='id_reporte', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='rescue.reporte')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision_metros', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ReporteUbicacion',
                'constraints': [models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='ck_reporte_latitud'), models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='ck_reporte_longitud')],
            },
        ),
        migrations.AddConstraint(
            model_name='reporte',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('codigo_gestion_hash', ''), ('usuario_reportante__isnull', False)), models.Q(('usuario_reportante__isnull', True), models.Q(('codigo_gestion_hash', ''), _negated=True)), _connector='OR'), name='ck_reporte_identidad'),
        ),
        migrations.AddConstraint(
            model_name='casorescate',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_cierre__isnull', True), ('fecha_cierre__gte', models.F('fecha_aceptacion')), _connector='OR'), name='ck_caso_fechas'),
        ),
    ]
