# Generated by Django 5.2.18 on 2026-10-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0002_spatial_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='casorescate',
            name='ocupa_cupo',
            field=models.BooleanField(default=True),
        ),
    ]
