# Generated by Django 5.2.18 on 2026-10-08 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_sponsorship'),
        ('rescue', '0003_casorescate_ocupa_cupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apadrinamiento',
            fields=[
                ('id_apadrinamiento', models.AutoField(primary_key=True, serialize=False)),
                ('monto_comprometido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_compromiso', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('estado_apadrinamiento', models.ForeignKey(db_column='id_estado_apadrinamiento', on_delete=django.db.models.deletion.PROTECT, to='core.valormaestro')),
                ('reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.PROTECT, to='rescue.reporte')),
                ('usuario_padrino', models.ForeignKey(db_column='id_usuario_padrino', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Apadrinamiento',
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionAporte',
            fields=[
                ('id_confirmacion', models.AutoField(primary_key=True, serialize=False)),
                ('monto_confirmado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('apadrinamiento', models.ForeignKey(db_column='id_apadrinamiento', on_delete=django.db.models.deletion.PROTECT, to='rescue.apadrinamiento')),
                ('usuario_confirmador', models.ForeignKey(db_column='id_usuario_confirmador', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ConfirmacionAporte',
            },
        ),
        migrations.CreateModel(
            name='CuentaFundacion',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuenta_cifrado', models.BinaryField()),
                ('numero_cuenta_ultimos4', models.CharField(max_length=4)),
                ('banco', models.CharField(max_length=120)),
                ('tipo_cuenta', models.CharField(max_length=60)),
                ('titular', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fundacion', models.ForeignKey(db_column='id_fundacion', on_delete=django.db.models.deletion.PROTECT, to='core.fundacion')),
            ],
            options={
                'db_table': 'CuentaFundacion',
            },
        ),
        migrations.CreateModel(
            name='CuentaRevelada',
            fields=[
                ('id_cuenta_revelada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_revelacion', models.DateTimeField(auto_now_add=True)),
                ('apadrinamiento', models.ForeignKey(db_column='id_apadrinamiento', on_delete=django.db.models.deletion.PROTECT, to='rescue.apadrinamiento')),
                ('cuenta', models.ForeignKey(db_column='id_cuenta', on_delete=django.db.models.deletion.PROTECT, to='rescue.cuentafundacion')),
            ],
            options={
                'db_table': 'CuentaRevelada',
            },
        ),
        migrations.CreateModel(
            name='DeclaracionTransferencia',
            fields=[
                ('id_declaracion', models.AutoField(primary_key=True, serialize=False)),
                ('monto_declarado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia_cifrada', models.BinaryField(blank=True, null=True)),
                ('fecha_transferencia_declarada', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('apadrinamiento', models.ForeignKey(db_column='id_apadrinamiento', on_delete=django.db.models.deletion.PROTECT, to='rescue.apadrinamiento')),
                ('evidencia', models.ForeignKey(blank=True, db_column='id_archivo_evidencia', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.archivodigital')),
            ],
            options={
                'db_table': 'DeclaracionTransferencia',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoApadrinamiento',
            fields=[
                ('id_historial_apadrinamiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('apadrinamiento', models.ForeignKey(db_column='id_apadrinamiento', on_delete=django.db.models.deletion.PROTECT, to='rescue.apadrinamiento')),
                ('estado_anterior', models.ForeignKey(blank=True, db_column='id_estado_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apadrinamientos_historial_anterior', to='core.valormaestro')),
                ('estado_nuevo', models.ForeignKey(db_column='id_estado_nuevo', on_delete=django.db.models.deletion.PROTECT, related_name='apadrinamientos_historial_nuevo', to='core.valormaestro')),
                ('usuario_actor', models.ForeignKey(db_column='id_usuario_actor', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HistorialEstadoApadrinamiento',
            },
        ),
        migrations.AddConstraint(
            model_name='apadrinamiento',
            constraint=models.CheckConstraint(condition=models.Q(('monto_comprometido__gt', 0)), name='ck_apad_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='confirmacionaporte',
            constraint=models.CheckConstraint(condition=models.Q(('monto_confirmado__gt', 0)), name='ck_conf_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cuentarevelada',
            constraint=models.UniqueConstraint(fields=('apadrinamiento', 'cuenta'), name='uq_cuenta_revelada'),
        ),
        migrations.AddConstraint(
            model_name='declaraciontransferencia',
            constraint=models.CheckConstraint(condition=models.Q(('monto_declarado__gt', 0)), name='ck_decl_monto_positivo'),
        ),
    ]
