# Generated by Django 5.2.18 on 2026-10-08 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_rescue_catalogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Especie',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('especie', models.ForeignKey(db_column='id_especie', on_delete=django.db.models.deletion.PROTECT, to='animals.especie')),
            ],
            options={
                'db_table': 'Raza',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('es_estimada', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.ForeignKey(blank=True, db_column='id_dueno', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mascotas_propias', to=settings.AUTH_USER_MODEL)),
                ('estado_mascota', models.ForeignKey(db_column='id_estado_mascota', on_delete=django.db.models.deletion.PROTECT, related_name='mascotas_estado', to='core.valormaestro')),
                ('sexo', models.ForeignKey(blank=True, db_column='id_sexo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mascotas_sexo', to='core.valormaestro')),
                ('tamano', models.ForeignKey(blank=True, db_column='id_tamano', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mascotas_tamano', to='core.valormaestro')),
                ('raza', models.ForeignKey(db_column='id_raza', on_delete=django.db.models.deletion.PROTECT, to='animals.raza')),
            ],
            options={
                'db_table': 'Mascota',
            },
        ),
        migrations.AddConstraint(
            model_name='raza',
            constraint=models.UniqueConstraint(fields=('especie', 'nombre'), name='uq_raza_especie_nombre'),
        ),
        migrations.AddConstraint(
            model_name='mascota',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_nacimiento__isnull', False), ('es_estimada', False), _connector='OR'), name='ck_mascota_fecha_estimada'),
        ),
    ]
