# Generated by Django 5.2.18 on 2026-10-08 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('core', '0003_seed_sponsorship'),
        ('rescue', '0004_apadrinamiento_confirmacionaporte_cuentafundacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.OneToOneField(db_column='id_archivo', on_delete=django.db.models.deletion.PROTECT, to='core.archivodigital')),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.PROTECT, to='animals.mascota')),
                ('tipo_documento', models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.PROTECT, to='core.valormaestro')),
            ],
            options={
                'db_table': 'DocumentoAdjunto',
            },
        ),
        migrations.CreateModel(
            name='AutorizacionExpediente',
            fields=[
                ('id_autorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_otorgamiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.PROTECT, to='animals.mascota')),
                ('usuario_otorgante', models.ForeignKey(db_column='id_usuario_otorgante', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('veterinario', models.ForeignKey(db_column='id_veterinario', on_delete=django.db.models.deletion.PROTECT, to='core.veterinario')),
            ],
            options={
                'db_table': 'AutorizacionExpediente',
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_expiracion__gt', models.F('fecha_otorgamiento'))), name='ck_autorizacion_vigencia'), models.CheckConstraint(condition=models.Q(('fecha_revocacion__isnull', True), ('fecha_revocacion__gte', models.F('fecha_otorgamiento')), _connector='OR'), name='ck_autorizacion_revocacion')],
            },
        ),
        migrations.CreateModel(
            name='CodigoQRExpediente',
            fields=[
                ('id_qr', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_hash', models.CharField(max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.PROTECT, to='animals.mascota')),
                ('usuario_creador', models.ForeignKey(db_column='id_usuario_creador', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CodigoQRExpediente',
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_expiracion__gt', models.F('fecha_creacion'))), name='ck_qr_vigencia')],
            },
        ),
        migrations.CreateModel(
            name='CustodiaMascota',
            fields=[
                ('id_custodia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('caso', models.ForeignKey(blank=True, db_column='id_caso_origen', null=True, on_delete=django.db.models.deletion.PROTECT, to='rescue.casorescate')),
                ('fundacion', models.ForeignKey(db_column='id_fundacion', on_delete=django.db.models.deletion.PROTECT, to='core.fundacion')),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.PROTECT, to='animals.mascota')),
                ('usuario_registrador', models.ForeignKey(db_column='id_usuario_registrador', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CustodiaMascota',
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='ck_custodia_fechas')],
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id_historial_medico', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.TextField()),
                ('nombre_veterinario_externo', models.CharField(blank=True, max_length=150)),
                ('registro_profesional_externo', models.CharField(blank=True, max_length=80)),
                ('fecha_atencion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.PROTECT, to='animals.mascota')),
                ('usuario_registrador', models.ForeignKey(db_column='id_usuario_registrador', on_delete=django.db.models.deletion.PROTECT, related_name='registros_medicos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_verificador', models.ForeignKey(blank=True, db_column='id_usuario_verificador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_medicos_verificados', to=settings.AUTH_USER_MODEL)),
                ('veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.veterinario')),
            ],
            options={
                'db_table': 'HistorialMedico',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('nombre_veterinario_externo', ''), ('registro_profesional_externo', ''), ('veterinario__isnull', False)), models.Q(('usuario_verificador__isnull', False), ('veterinario__isnull', True), models.Q(('nombre_veterinario_externo', ''), _negated=True), models.Q(('registro_profesional_externo', ''), _negated=True)), _connector='OR'), name='ck_medico_profesional')],
            },
        ),
    ]
