# Generated by Django 5.2.18 on 2026-10-08 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadVerificable',
            fields=[
                ('id_entidad_verificable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'EntidadVerificable',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Permiso',
            },
        ),
        migrations.CreateModel(
            name='TipoMaestro',
            fields=[
                ('id_tipo_maestro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TipoMaestro',
            },
        ),
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('entidad', models.OneToOneField(db_column='id_entidad_verificable', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.entidadverificable')),
                ('nit_documento', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Anunciante',
            },
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('entidad', models.OneToOneField(db_column='id_entidad_verificable', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.entidadverificable')),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Fundacion',
            },
        ),
        migrations.CreateModel(
            name='ArchivoDigital',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('url_archivo', models.URLField(blank=True, max_length=2048)),
                ('mime_type', models.CharField(max_length=120)),
                ('tamano_bytes', models.PositiveBigIntegerField()),
                ('visibilidad', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PRIVADO', max_length=7)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('usuario_cargador', models.ForeignKey(blank=True, db_column='id_usuario_cargador', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArchivoDigital',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('departamento', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'Ciudad',
                'constraints': [models.UniqueConstraint(fields=('departamento', 'nombre'), name='uq_ciudad_departamento_nombre')],
            },
        ),
        migrations.CreateModel(
            name='EntidadMiembro',
            fields=[
                ('id_entidad_miembro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('entidad', models.ForeignKey(db_column='id_entidad_verificable', on_delete=django.db.models.deletion.PROTECT, to='core.entidadverificable')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EntidadMiembro',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('ambito', models.CharField(choices=[('GLOBAL', 'Global'), ('ENTIDAD', 'Entidad')], max_length=7)),
            ],
            options={
                'db_table': 'Rol',
                'constraints': [models.CheckConstraint(condition=models.Q(('ambito__in', ['GLOBAL', 'ENTIDAD'])), name='ck_rol_ambito')],
            },
        ),
        migrations.CreateModel(
            name='EntidadMiembroRol',
            fields=[
                ('id_entidad_miembro_rol', models.AutoField(primary_key=True, serialize=False)),
                ('miembro', models.ForeignKey(db_column='id_entidad_miembro', on_delete=django.db.models.deletion.PROTECT, to='core.entidadmiembro')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
            options={
                'db_table': 'EntidadMiembroRol',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.PROTECT, to='core.permiso')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
            options={
                'db_table': 'RolPermiso',
            },
        ),
        migrations.CreateModel(
            name='SolicitudValidacion',
            fields=[
                ('id_solicitud_validacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(db_column='id_entidad_verificable', on_delete=django.db.models.deletion.PROTECT, to='core.entidadverificable')),
                ('usuario_solicitante', models.ForeignKey(db_column='id_usuario_solicitante', on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_validador', models.ForeignKey(blank=True, db_column='id_usuario_validador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SolicitudValidacion',
            },
        ),
        migrations.CreateModel(
            name='DocumentoValidacion',
            fields=[
                ('id_documento_validacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.OneToOneField(db_column='id_archivo', on_delete=django.db.models.deletion.PROTECT, to='core.archivodigital')),
                ('usuario_cargador', models.ForeignKey(db_column='id_usuario_cargador', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(db_column='id_solicitud_validacion', on_delete=django.db.models.deletion.PROTECT, to='core.solicitudvalidacion')),
            ],
            options={
                'db_table': 'DocumentoValidacion',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id_usuario_rol', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsuarioRol',
            },
        ),
        migrations.CreateModel(
            name='ValorMaestro',
            fields=[
                ('id_valor_maestro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.ForeignKey(db_column='id_tipo_maestro', on_delete=django.db.models.deletion.PROTECT, to='core.tipomaestro')),
            ],
            options={
                'db_table': 'ValorMaestro',
            },
        ),
        migrations.AddField(
            model_name='solicitudvalidacion',
            name='estado_solicitud',
            field=models.ForeignKey(db_column='id_estado_solicitud', on_delete=django.db.models.deletion.PROTECT, to='core.valormaestro'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo_notificacion', models.ForeignKey(db_column='id_tipo_notificacion', on_delete=django.db.models.deletion.PROTECT, to='core.valormaestro')),
            ],
            options={
                'db_table': 'Notificacion',
            },
        ),
        migrations.AddField(
            model_name='entidadverificable',
            name='estado_verificacion',
            field=models.ForeignKey(db_column='id_estado_verificacion', on_delete=django.db.models.deletion.PROTECT, to='core.valormaestro'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.ForeignKey(db_column='id_ciudad', on_delete=django.db.models.deletion.PROTECT, to='core.ciudad')),
            ],
            options={
                'db_table': 'Zona',
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('entidad', models.OneToOneField(db_column='id_entidad_verificable', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.entidadverificable')),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.ForeignKey(db_column='id_ciudad', on_delete=django.db.models.deletion.PROTECT, to='core.ciudad')),
            ],
            options={
                'db_table': 'Clinica',
            },
        ),
        migrations.CreateModel(
            name='FundacionZona',
            fields=[
                ('id_fundacion_zona', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.PROTECT, to='core.zona')),
                ('fundacion', models.ForeignKey(db_column='id_fundacion', on_delete=django.db.models.deletion.PROTECT, to='core.fundacion')),
            ],
            options={
                'db_table': 'FundacionZona',
            },
        ),
        migrations.AddField(
            model_name='fundacion',
            name='ciudad',
            field=models.ForeignKey(db_column='id_ciudad', on_delete=django.db.models.deletion.PROTECT, to='core.ciudad'),
        ),
        migrations.CreateModel(
            name='CapacidadFundacion',
            fields=[
                ('id_capacidad', models.AutoField(primary_key=True, serialize=False)),
                ('cupos_totales', models.PositiveSmallIntegerField()),
                ('cupos_ocupados', models.PositiveSmallIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_actualizador', models.ForeignKey(db_column='id_usuario_actualizador', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fundacion', models.OneToOneField(db_column='id_fundacion', on_delete=django.db.models.deletion.PROTECT, to='core.fundacion')),
            ],
            options={
                'db_table': 'CapacidadFundacion',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('entidad', models.OneToOneField(db_column='id_entidad_verificable', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.entidadverificable')),
                ('direccion', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.ForeignKey(db_column='id_ciudad', on_delete=django.db.models.deletion.PROTECT, to='core.ciudad')),
            ],
            options={
                'db_table': 'Tienda',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('entidad', models.OneToOneField(db_column='id_entidad_verificable', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.entidadverificable')),
                ('registro_profesional', models.CharField(max_length=80, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('clinica', models.ForeignKey(blank=True, db_column='id_clinica', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clinica')),
                ('usuario_profesional', models.OneToOneField(db_column='id_usuario_profesional', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Veterinario',
            },
        ),
        migrations.AddConstraint(
            model_name='entidadmiembro',
            constraint=models.UniqueConstraint(fields=('entidad', 'usuario'), name='uq_entidad_miembro'),
        ),
        migrations.AddConstraint(
            model_name='entidadmiembro',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_salida__isnull', True), ('fecha_salida__gte', models.F('fecha_ingreso')), _connector='OR'), name='ck_entidad_miembro_fechas'),
        ),
        migrations.AddConstraint(
            model_name='entidadmiembrorol',
            constraint=models.UniqueConstraint(fields=('miembro', 'rol'), name='uq_entidad_miembro_rol'),
        ),
        migrations.AddConstraint(
            model_name='rolpermiso',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='uq_rol_permiso'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol'), name='uq_usuario_rol'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_revocacion__isnull', True), ('fecha_revocacion__gte', models.F('fecha_asignacion')), _connector='OR'), name='ck_usuario_rol_fechas'),
        ),
        migrations.AddConstraint(
            model_name='valormaestro',
            constraint=models.UniqueConstraint(fields=('tipo', 'nombre'), name='uq_valor_tipo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='solicitudvalidacion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_resolucion__isnull', True), ('fecha_resolucion__gte', models.F('fecha_solicitud')), _connector='OR'), name='ck_validacion_fechas'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'fecha_creacion'], name='ix_notif_usuario_fecha'),
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(fields=('ciudad', 'nombre'), name='uq_zona_ciudad_nombre'),
        ),
        migrations.AddConstraint(
            model_name='fundacionzona',
            constraint=models.UniqueConstraint(fields=('fundacion', 'zona'), name='uq_fundacion_zona'),
        ),
        migrations.AddConstraint(
            model_name='capacidadfundacion',
            constraint=models.CheckConstraint(condition=models.Q(('cupos_ocupados__lte', models.F('cupos_totales'))), name='ck_capacidad_cupos'),
        ),
    ]
